---
branches:
  - main
  - { name: next, prerelease: true }
tagFormat: v${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - { breaking: true, release: major }
        - { type: feat, release: minor }
        - { type: refactor, scope: "core*", release: minor }
        - { revert: true, release: patch }
        - { type: build, release: patch }
        - { type: ci, release: patch }
        - { type: deps, release: patch }
        - { type: fix, release: patch }
        - { type: perf, release: patch }
        - { type: refactor, release: patch }
        - { type: chore, release: false }
        - { type: docs, release: false }
        - { type: style, release: false }
        - { scope: no-release, release: false }

  - - "@semantic-release/release-notes-generator"
    - preset: angular

  - - "@semantic-release/npm"
    - npmPublish: false

  - - "@aensley/semantic-release-openapi"
    - apiSpecFiles: ["schemas/OpenAPI/open-api.yaml"]

  - - "@semantic-release/github"
    - addReleases: bottom
      assignees: trevor-anderson
      successComment: false
      failTitle: false
      # The options set to `false` above ensure the github plugin does not
      # attempt to use the GitHub API in the "success" step, which currently
      # throws every single time due to purported rate limiting issues with the
      # GitHub API, even though local usage does not result in such errors. The
      # problem is suspected to be caused by how the plugin uses Octokit's `retry`.
      # See issues:
      # - https://github.com/semantic-release/semantic-release/issues/2204
      # - https://github.com/semantic-release/semantic-release/issues/843

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
      changelogTitle: |-
        # Changelog

        All notable changes to this project will be documented in this file.

        ---

  - - "@semantic-release/git"
    - message: "chore(release): version ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      assets:
        - "CHANGELOG.md"
        - "package.json"
        - "package-lock.json"
        - "npm-shrinkwrap.json"
        - "schemas/OpenAPI/open-api.yaml"
