import gql from "graphql-tag";

export const typeDefs = gql`
  """
  User is an implementation of the FixitUser interface which includes
  both the publicly-accessible FixitUser/Contact fields as well as
  private fields which are only available to the user which created
  the account.
  """
  type User implements FixitUser {
    """
    User ID internally identifies individual User accounts
    """
    id: ID!
    """
    Public-facing handle identifies users to other users (e.g., "@joe")
    """
    handle: String!
    """
    User's own email address
    """
    email: Email!
    """
    User's own phone number
    """
    phone: String!
    """
    User's own Profile object
    """
    profile: Profile!
    """
    User's Stripe Customer ID (defined and generated by Stripe)
    """
    stripeCustomerID: String!
    """
    User Subscription info
    """
    subscription: UserSubscription
    """
    User Stripe Connect Account info
    """
    stripeConnectAccount: UserStripeConnectAccount
    """
    Account creation timestamp
    """
    createdAt: DateTime!
  }

  extend type Query {
    user: User!
  }
`;
