name: 📝 Annual License Update

on:
  # This workflow runs on Jan 1st every year
  schedule:
    - cron: "0 0 1 1 *"

jobs:
  update-license:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to checkout the code and update the LICENSE file
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Update Copyright Date Range in LICENSE
        run: |
          function log_error() { echo '🚨LICENSE UPDATE FAILED🚨'; exit 1; }

          year=$(date +%Y)

          sed -i -E \
              "s/(Copyright © [0-9]{4})-[0-9]{4}(.*)/\1-$year\2/" ./LICENSE || log_error

          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add ./LICENSE

          git commit -m \
              "chore(license): update copyright date range to include $year" || log_error

          echo 'License Copyright date range successfully updated.'
