import { UUID_V1_REGEX_STR } from "@utils/regex";

export const USER_ID_PREFIX_STR = "USER";
export const USER_ID_REGEX_STR = `${USER_ID_PREFIX_STR}#${UUID_V1_REGEX_STR}`;
export const USER_ID_REGEX = new RegExp(`^${USER_ID_REGEX_STR}$`);

export const USER_SK_PREFIX_STR = "#DATA";
export const USER_SK_REGEX = new RegExp(`^${USER_SK_PREFIX_STR}#${USER_ID_REGEX_STR}$`);

/**
 * User `handle`:
 * - Is case sensitive
 * - Must begin with "@" symbol
 * - After the "@" symbol, there must be between 3-50 characters
 * - Permitted characters:
 *   - Uppercase letters (english alphabet)
 *   - Lowercase letters (english alphabet)
 *   - Numbers
 *   - Underscores
 */
export const USER_HANDLE_REGEX = /^@[a-zA-Z0-9_]{3,50}$/;

/**
 * User `stripeCustomerID`:
 * - Defined and generated by Stripe
 * - Must begin with "cus_", followed by 10+ alphanumeric characters
 * - Example from Stripe docs: `"cus_IiU67YFNrznvI3"`
 */
export const USER_STRIPE_CUSTOMER_ID_REGEX = /^cus_[a-zA-Z0-9]{10,}$/;
